version: "3.9"

services:
  db:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: ${PROJECT:-projectname}-db
    env_file: db.env
    ports:
      - ${EXTERNAL_PORT:-5432}:5432

  redis:
    image: redis/redis-stack:7.2.0-v2
    container_name: ${PROJECT:-projectname}-redis
    restart: always
    env_file: redis.env
    ports:
      - ${EXTERNAL_PORT:-6379}:6379

  server:
    build:
      context: .
      target: production
    depends_on:
      - db
      - redis
    restart: always
    container_name: ${PROJECT:-projectname}-server
    volumes:
      - ./static:/opt/pysetup/src/static
      - ./media:/opt/pysetup/src/media
    env_file: .env
    ports:
      - ${SERVER_PORT:-8080}:8000

  open-api:
    build:
      context: .
      target: docs
    restart: always
    container_name: ${PROJECT:-projectname}-open-api
    env_file: .env
    platform: linux/amd64
    depends_on:
      - server
    ports:
      - ${RAPIDOC_PORT:-8090}:80

volumes:
  postgres_data:
